_wandb:
    value:
        cli_version: 0.22.3
        e:
            x4lefzqjipw7abpvn4hvl19mdtsw3nbf:
                args:
                    - --config
                    - config/model_config.yml
                    - --device
                    - cuda:0
                codePath: src/training/scripts/train_model.py
                codePathLocal: src/training/scripts/train_model.py
                cpu_count: 10
                cpu_count_logical: 20
                cudaVersion: "12.6"
                disk:
                    /:
                        total: "360076500992"
                        used: "54622478336"
                email: deepakns@iisc.ac.in
                executable: /home/deepakns/miniconda3/envs/MoK_date_predict/bin/python
                git:
                    commit: 1462bfa2e3b06135867210cf56236e3bcc2fecf9
                    remote: https://github.com/deepakns/MoK_date_predict.git
                gpu: Quadro RTX 8000
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-8316b53e-22c0-2f44-a764-7d49f5f23da3
                    - architecture: Turing
                      cudaCores: 4608
                      memoryTotal: "51539607552"
                      name: Quadro RTX 8000
                      uuid: GPU-9641fe0f-df31-9474-ccfd-f405d97b25bf
                host: cds
                memory:
                    total: "134721191936"
                os: Linux-5.15.0-119-generic-x86_64-with-glibc2.35
                program: /home/deepakns/Work/MoK_date_predict/src/training/scripts/train_model.py
                python: CPython 3.10.19
                root: /home/deepakns/Work/MoK_date_predict
                startedAt: "2025-11-06T03:58:03.268744Z"
                writerId: x4lefzqjipw7abpvn4hvl19mdtsw3nbf
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 54
            "2":
                - 1
                - 54
            "3":
                - 2
                - 15
                - 16
                - 61
                - 62
            "4": 3.10.19
            "5": 0.22.3
            "10":
                - 20
            "12": 0.22.3
            "13": linux-x86_64
data:
    value:
        augmentation:
            enabled: true
            height_shift_range: 0.1
            horizontal_flip: true
            rotation_range: 15
            width_shift_range: 0.1
        batch_size: 1
        data_dir: /gdata2/ERA5/monthly
        include_landsea: false
        include_lat: false
        include_lon: false
        input_geo_var_press:
            - u
            - v
        input_geo_var_surf:
            - sst
            - ttr
            - tcc
            - msl
        normalize_strategy: 1
        num_workers: 2
        pressure_levels:
            - 0
            - 1
        target_file: /home/deepakns/Work/data/MoKDates.csv
        test_years:
            - 2011:2024
        time_steps:
            - 1
            - 2
        train_years:
            - 1951:2000
        val_years:
            - 2001:2010
logging:
    value:
        log_dir: logs
        save_frequency: 1
        tensorboard: true
        wandb:
            enabled: true
            entity: null
            log_gradients: false
            log_model: true
            log_predictions: false
            name: null
            notes: Training directly with 0.01 to see performance
            project: MoK_date_predict
            tags:
                - with-scheduler
                - lr-0.01
                - batch_size-1
                - dropout-0.2
                - initial-kaiming-normal
            watch_freq: 100
            watch_log: gradients
            watch_model: false
model:
    value:
        architecture: SpatialProcessor
        dropout_rate: 0.2
        name: MoK_CNN_13
        spatial_input_shape:
            - 1440
            - 481
        target: 1
        weight_init:
            activation: relu
            bias_init: zeros
            bias_value: 0
            enabled: true
            gain: 1
            method: kaiming_normal
            mode: fan_out
            verbose: true
training:
    value:
        checkpoint:
            enabled: true
            monitor: val_loss
            save_best_only: true
        early_stopping:
            enabled: false
            monitor: val_loss
            patience: 10
        epochs: 100
        learning_rate: 0.01
        loss: mae
        lr_scheduler:
            enabled: false
            factor: 0.5
            min_lr: 1e-06
            mode: min
            patience: 5
            restore_best_on_reduce: true
            threshold: 0.0001
            type: ReduceLROnPlateau
        optimizer: adamw
        random_seed: 42
        weight_decay: 0.0001
